language: java
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIARL7RCF5MU7R6LCOK
  secret_access_key:
    secure: s6PYCQy99VjOwNYn13ehBB7QS/IcpXVaDoQ97L/Toi7u/bZ/eNNGdKDGMacShaO17dsFCDKZTioxKuOKPkFPBg127D7fChkr8tsG4NdQ+7kx0MNwcuPJ86paPdT5vHHam8RxIqlLEs3qse9uKHboH6oTsKBF8JQir/qL7cdatExlLWY0fKc5NYrwBtAOpHcznMR2unMlsd9Zz1VRY01G/mZ/A6Mar3vVDGKbzZwfaeUuAn6pYCqihW550inbl3YPg6N66lwIKY3bX9pdBhloPEVMGw/fU2gKedCOnFOvnq4zvfzqG+jjsCKdcqCafMy0UBXQJV/7aZORfym8Zm9u/PTJsiTW1VW7Sq/nTCWffSrV7PCquR/8yLf307d3VcIYvjfmJwCaTyTEiUT2FPm41+cRJoHzb1CmVvbBd1VYbGGTwlVBJxV2lG+kSHUc3dF08CjKRHA1iSelJw+GkXXzfHD+3ihhb8351WeyfP5BAfHS+sppH2F/1dZaou/Np+vFEVytwxFnVb+kiBiGd6cJqoDDGoF2GWMTsQseJFU9lj6bAGeDN/mQ8LOkOXNdvhMOn0j1m9ZBUHAI7AmJ8SxFLneUGmcsk/P1A53edjf9otknhLIQAlYx3j02narCn8Wqo1g6p36sEnBLZOF/13FCQ5UslOtRcB2ft7jkoD1Qr8M=
  region: ap-southeast-2
  app: Java-Blogging
  env: JavaBlogging-env
  bucket_name: java-bloggin-bucket
  on:
    repo: naabin/Java-Blogging
  skip_cleanup: 'true'
before_deploy:
  - mvn package